-- ============================================================
-- Lab 02 Assignment - Library Management System (Multi-table Joins)
-- Database: Oracle XE 18c
-- Course: CSE302 - Database Systems
-- University: East West University
-- Author: Samin Jawad
-- ============================================================

DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BORROW CASCADE CONSTRAINTS;

CREATE TABLE BOOK (

	BOOK_ID CHAR(6) PRIMARY KEY,
	TITLE VARCHAR2(50) NOT NULL,
	AUTHOR VARCHAR2(30),
	COPIES NUMBER DEFAULT 1,
	CONSTRAINT COPIES_CHK CHECK (COPIES > 0)

);

CREATE TABLE MEMBER (

	MEMBER_ID CHAR(5) PRIMARY KEY,
	NAME VARCHAR2(30) NOT NULL,
	CITY VARCHAR2(20),
	DATE_OF_BIRTH DATE

);

CREATE TABLE BORROW (

	BOOK_ID CHAR(6),
	MEMBER_ID CHAR(5),
	BORROW_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) ON DELETE CASCADE,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
	PRIMARY KEY (BOOK_ID, MEMBER_ID)

);


SELECT *FROM BOOK;
SELECT *FROM MEMBER;
SELECT *FROM BORROW;

ALTER TABLE BOOK
RENAME COLUMN COPIES TO AVAILABLE_COPIES;

ALTER TABLE MEMBER
ADD EMAIL VARCHAR(50) UNIQUE;

ALTER TABLE BOOK
ADD CONSTRAINT UNIQUE_AUTHOR UNIQUE (AUTHOR);


INSERT INTO BOOK VALUES ('B001', 'THE ODYSSEY', 'HOMER', 5);
INSERT INTO BOOK VALUES ('B002', '1984', 'GEORGE ORWELL', 3);
INSERT INTO BOOK VALUES ('B003', 'DATA STRUCTURES', 'MARK WEISS', 2);


INSERT INTO MEMBER VALUES ('M001', 'ALICE', 'DHAKA', TO_DATE('1995-04-12','YYYY-MM-DD'), 'alice@gmail.com');
INSERT INTO MEMBER VALUES ('M002', 'BOB', 'KHULNA', TO_DATE('1993-07-30','YYYY-MM-DD'), 'bob@gmail.com');
INSERT INTO MEMBER VALUES ('M003', 'CAROL', 'DHAKA', TO_DATE('1990-11-23','YYYY-MM-DD'), 'carol@gmail.com');
INSERT INTO MEMBER VALUES ('M004', 'DANIEL', 'CHITTAGONG', TO_DATE('1997-01-04','YYYY-MM-DD'), 'daniel@gmail.com');


INSERT INTO BORROW VALUES ('B001', 'M001', TO_DATE('2024-06-01','YYYY-MM-DD'));
INSERT INTO BORROW VALUES ('B002', 'M002', TO_DATE('2024-06-05','YYYY-MM-DD'));
INSERT INTO BORROW VALUES ('B003', 'M003', TO_DATE('2024-06-07','YYYY-MM-DD'));
INSERT INTO BORROW VALUES ('B001', 'M003', TO_DATE('2024-06-10','YYYY-MM-DD'));


--1. List all members’ names, cities, and emails.
SELECT NAME, CITY, EMAIL
FROM MEMBER;


--2. Find unique cities where members live.
SELECT UNIQUE CITY
FROM MEMBER;

--3. List all books with more than 2 available copies.
SELECT *
FROM BOOK
WHERE AVAILABLE_COPIES > 2;

--4. Find all members who live in Dhaka.
SELECT *
FROM MEMBER
WHERE CITY = 'DHAKA';

--5. Find all members who do not live in Khulna.
SELECT *
FROM MEMBER
WHERE CITY != 'KHULNA';

--6. Find members (IDs) who borrowed the book titled ’The Odyssey’.
SELECT *
FROM BORROW NATURAL JOIN BOOK;

SELECT MEMBER_ID
FROM BORROW, BOOK
WHERE BORROW.BOOK_ID = BOOK.BOOK_ID AND BOOK.TITLE = 'THE ODYSSEY';

--7. List member’s name and their borrowed book IDs, who borrowed books after 2024-06-05.
SELECT *
FROM MEMBER NATURAL JOIN BORROW;

SELECT NAME, BOOK_ID
FROM MEMBER, BORROW
WHERE MEMBER.MEMBER_ID = BORROW.MEMBER_ID AND BORROW.BORROW_DATE > TO_DATE('2024-06-05','YYYY-MM-DD');

--8. Find all borrow records for member M003.
SELECT *
FROM BORROW NATURAL JOIN BOOK NATURAL JOIN MEMBER;

SELECT BORROW.MEMBER_ID, MEMBER.NAME, BOOK.TITLE, BOOK.AUTHOR, BOOK.BOOK_ID, BORROW.BORROW_DATE
FROM BORROW, BOOK, MEMBER
WHERE BORROW.MEMBER_ID = MEMBER.MEMBER_ID AND BORROW.BOOK_ID = BOOK.BOOK_ID AND BORROW.MEMBER_ID = 'M003';

--9. Find all book IDs borrowed by members living in Dhaka.
SELECT *
FROM BORROW NATURAL JOIN MEMBER;

SELECT BORROW.BOOK_ID
FROM BORROW, MEMBER
WHERE BORROW.MEMBER_ID = MEMBER.MEMBER_ID AND MEMBER.CITY = 'DHAKA';

--10. Find members who have never borrowed any book.
SELECT *
FROM MEMBER
WHERE MEMBER_ID NOT IN (SELECT MEMBER_ID FROM BORROW);

