-- ============================================================
-- Lab 02 - Constraints, Joins & Schema Alteration
-- Database: Oracle XE 18c
-- Course: CSE302 - Database Systems
-- University: East West University
-- Author: Samin Jawad
-- ============================================================

DROP TABLE LIBRARY CASCADE CONSTRAINTS; --Doesn't Matter there is a contraint or not, it will be droped
DROP TABLE BOOK CASCADE CONSTRAINTS; --Doesn't Matter there is a contraint or not, it will be droped

CREATE TABLE LIBRARY(
    
    LIBRARY_ID VARCHAR2(10) PRIMARY KEY, --Easy way to define primary key
    NAME VARCHAR2 (30) NOT NULL, -- This can not be null, Have to input
    LOCATION VARCHAR2 (50),
    CAPACITY NUMBER DEFAULT 5000, -- If nothing inserted iw will be dafault 5000
    -- CONSTRAINT LIB_ID_PK PRIMARY KEY (LIBRARY_ID) -- Complex way to define primary key
    CONSTRAINT CAPACITY_CHECK CHECK(CAPACITY > 0) --Check whether the capacityb is more than 0 or not, if not the info will not created

);

SELECT *
FROM USER_CONS_COLUMNS --Track constraints from tables, it is a metadata from databse
WHERE TABLE_NAME = 'LIBRARY';


INSERT INTO LIBRARY VALUES ('L001','ABC LIBRARY','AFTABNAGAR',9999);
INSERT INTO LIBRARY (LIBRARY_ID,NAME) VALUES ('L002','XYZ LIBRARY');
INSERT INTO LIBRARY (LIBRARY_ID,CAPACITY,NAME) VALUES ('L003',5678,'FGH LIBRARY'); -- Just want to add these three values

SELECT *
FROM LIBRARY;

UPDATE LIBRARY
SET LOCATION = 'DHANMONDI'
WHERE LIBRARY_ID = 'L003';



CREATE TABLE BOOK(
    
    BOOK_ID VARCHAR2(10) PRIMARY KEY, --Easy way to define primary key
    TITLE VARCHAR2 (30) NOT NULL, -- This can not be null, Have to input
    LIBRARY_ID VARCHAR2 (50),
    COPIES NUMBER,
    CONSTRAINT COPIES_CHECK CHECK(COPIES >= 1), --Check whether the capacityb is more than 0 or not, if not the info will not created
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (LIBRARY_ID) --Foreign Key Defined
    
);

INSERT INTO BOOK VALUES ('B001','HOME BEFORE DARK','L001',1500);
INSERT INTO BOOK VALUES ('B002','THE SILENT PATIENT','L002',2800);
INSERT INTO BOOK VALUES ('B003','CRAVEN MANOR','L001',500);
INSERT INTO BOOK VALUES ('B004','THE EXORCIST','L003', 1000);

SELECT *
FROM BOOK;

-- ADDING A NEW COLUMN 'AUTHOR' IN BOOK TABLE
ALTER TABLE BOOK
ADD AUTHOR VARCHAR (30);

--RENAME TITLE COLUMN TO BOOK_NAME IN BOOK TABLE
ALTER TABLE BOOK
RENAME COLUMN TITLE TO BOOK_NAME;

--FIND ALL THE INFORMATIONS OF THE BOOK NAMED 'HOME BEFORE DARK'
SELECT *
FROM BOOK
WHERE BOOK_NAME = 'HOME BEFORE DARK';

--FIND THE LOCATION AND CAPACITY OF L001
SELECT LOCATION, CAPACITY
FROM LIBRARY
WHERE LIBRARY_ID = 'L001'

-- CROSS JOIN TWO TABLES & FILTERING
SELECT * 
FROM LIBRARY, BOOK
WHERE LIBRARY.LIBRARY_ID = BOOK.LIBRARY_ID; --FILTERING

--NATURAL JOIN
SELECT *
FROM LIBRARY NATURAL JOIN BOOK;

--FIND THE LIBRARY NAME WHERE 'CRAVEN MANOR' IS LOCATED
SELECT * 
FROM LIBRARY, BOOK
WHERE LIBRARY.LIBRARY_ID = BOOK.LIBRARY_ID AND BOOK.BOOK_NAME = 'CRAVEN MANOR';

--FIND BOOK IDs AVAILABLE IN DHANMONDI
SELECT BOOK_ID 
FROM LIBRARY, BOOK
WHERE LIBRARY.LIBRARY_ID = BOOK.LIBRARY_ID AND LOCATION = 'DHANMONDI';