-- ============================================================
-- Lab 01 - DDL & DML Fundamentals (CREATE, SELECT, UPDATE, INSERT, DELETE)
-- Database: Oracle XE 18c
-- Course: CSE302 - Database Systems
-- University: East West University
-- Author: Samin Jawad
-- ============================================================

DROP TABLE STUDENT CASCADE CONSTRAINTS; -- DROP A TABLE IF EXISTS

-- CREATE A TABLE
CREATE TABLE STUDENT(

STUDENT_ID CHAR(13),
STUDENT_NAME VARCHAR2(30),
STUDENT_GENDER CHAR(1),
STUDENT_CREDIT NUMBER,
STUDENT_CGPA NUMERIC(3,2),
STUDENT_DOB DATE,
STUDENT_PHONE CHAR(11)

);

SELECT *FROM STUDENT; -- VIEW FULL TABLE
DESC STUDENT; -- VIEW THE TABLE DESCRIPTION
SELECT STUDENT_NAME,STUDENT_CGPA FROM STUDENT; --JUST SHOW THOSE TWO COLUMNS
SELECT *FROM STUDENT WHERE STUDENT_CGPA>3.90; -- SHOW STUDENTS WHOS CGPAIS GREATER THAN 3.90

SELECT STUDENT_NAME, STUDENT_DOB FROM STUDENT WHERE STUDENT_GENDER='F' AND STUDENT_CREDIT<90; --STUDENT NAME AND DOB OF FEMALE STUDENTS WHO COMPLETED LESS THAN 90 CREDITS

UPDATE STUDENT SET STUDENT_CGPA = 3.99 WHERE STUDENT_ID = '2024-3-60-544'; -- UPDATE SAMIN JAWAD'S CGPA TO 3.99 WITH STUDENT ID
UPDATE STUDENT SET STUDENT_CREDIT = STUDENT_CREDIT+10 WHERE STUDENT_GENDER='F'; -- INCREASE THE FEMALE STUDENT'S CREDIT BY 10

-- ADDING VALUES
INSERT INTO STUDENT VALUES ('2024-3-60-544', 'SAMIN JAWAD', 'M', 63.5, 3.95, TO_DATE('08-09-2005','MM-DD-YYYY'), '01XXXXXXXXX');
INSERT INTO STUDENT VALUES ('2024-3-60-542', 'TASBIHUN NUHAT', 'M', 63.5, 3.75, TO_DATE('01-01-2004','MM-DD-YYYY'), '01XXXXXXXXX');
INSERT INTO STUDENT VALUES ('2024-3-60-549', 'RAGEEB YASAR', 'M', 63.5, 3.85, TO_DATE('04-03-2003','MM-DD-YYYY'), '01XXXXXXXXX');
INSERT INTO STUDENT VALUES ('2024-3-60-243', 'TAHSIN AHMED', 'M', 63.5, 3.91, TO_DATE('04-21-2004','MM-DD-YYYY'), '01XXXXXXXXX');
INSERT INTO STUDENT VALUES ('2024-3-60-243', 'NOWRIN', 'F', 65.5, 3.91, TO_DATE('04-21-2004','MM-DD-YYYY'), '01XXXXXXXXX');
INSERT INTO STUDENT VALUES ('2024-3-60-243', 'AFIA', 'F', 100, 3.91, TO_DATE('04-21-2004','MM-DD-YYYY'), '01XXXXXXXXX');

DELETE FROM STUDENT WHERE STUDENT_GENDER = 'F'; -- DELETE ROW'S WHERE STUDENT'S GENDER IS FEMALE

COMMIT;-- SAVE THE DATABASE INTO THE MAIN STORAGE